apiVersion: batch/v1
kind: CronJob
metadata:
  name: naver-blog
spec:
  schedule: "0 13 * * *"  # ⏰ Run daily at 9AM ET (13:00 UTC)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: naver-blog
            image: 453004141968.dkr.ecr.us-east-1.amazonaws.com/naver-blog:latest
            env:
              - name: OPENAI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: quiz-secrets
                    key: OPENAI_API_KEY
              - name: DISCORD_BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: quiz-secrets
                    key: DISCORD_BOT_TOKEN
              - name: DISCORD_CHANNEL_ID
                valueFrom:
                  secretKeyRef:
                    name: quiz-secrets
                    key: DISCORD_CHANNEL_ID
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
