name: Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    name: Build Go App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Build app
        run: go build -v ./...
