name: Run CronJob Manually

on:
  workflow_dispatch:

jobs:
  run-cronjob:
    name: Trigger Job from CronJob Template
    runs-on: ubuntu-latest

    steps:
      - name: Run CronJob Immediately via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Triggering one-off Job from CronJob..."
            sudo kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml create job \
              --from=cronjob/naver-blog manual-run-$(date +%s)

            echo "Current Jobs:"
            sudo kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get jobs
